export const WeatherActionTypes = {
  GET_WEATHER: "GET_WEATHER",
  CHANGE_LIGHT: "CHANGE_LIGHT",
  HANDLE_CHANGE: "HANDLE_CHANGE",
  CHANGE_WEATHER: "CHANGE_WEATHER",
  TOGGLE_VISIBLE: "TOGGLE_VISIBLE",
  REQUEST_WEATHER_FAILED: "REQUEST_WEATHER_FAILED",
  REQUEST_WEATHER_PENDING: "REQUEST_WEATHER_PENDING",
  REQUEST_WEATHER_SUCCESS: "REQUEST_WEATHER_SUCCESS",
};
