export const ActivitiesActionTypes = {
    SET_DEFINED: "SET_DEFINED",
    TOGGLE_MODAL: "TOGGLE_MODAL",
    HANDLE_CHANGE: "HANDLE_CHANGE",
    ADD_ACTIVITIES: "ADD_ACTIVITIES",
    SORT_ACTIVITIES: "SORT_ACTIVITIES",
    UPDATE_ACTIVITY: "UPDATE_ACTIVITY",
    DELETE_ACTIVITY: "DELETE_ACTIVITY",
    SORT_CHECK_ACTIVITY: "SORT_CHECK_ACTIVITY",
    SORT_ACTIVE_ACTIVITIES: "SORT_ACTIVE_ACTIVITIES",
    SET_DECREAMENT_MINUTES: "SET_DECREAMENT_MINUTES",
    SET_ARCHRIVE_ACTIVITIES: "SET_ARCHRIVE_ACTIVITIES",
    SORT_NONACTIVE_ACTIVITIES: "SORT_NONACTIVE_ACTIVITIES",
  };
  